Repository PrograMemo-Groom/instagram-clone, pull requests merged in 2024-12, with the labels that each got.

#36 :art: 게시글 정사각형 프레임 유지하도록 변경
  src/components/posts/Posts.jsx
Labels: 리팩토링

#37 ✨ 로그인 페이지 구현 (UI/UX 구현 및 페이지 이동)
  package-lock.json
  package.json
  src/App.jsx
  src/assets/login/facebook.svg
  src/assets/login/login-img.svg
  src/assets/login/loginImg1.png
  src/assets/login/loginImg2.png
  src/assets/login/loginImg3.png
  src/assets/login/loginImg4.png
  src/assets/login/showPassword.svg
  src/assets/login/unShowPassword.svg
  src/components/login/LoginForm.jsx
  src/components/login/imgConfig.js
  src/pages/login/ForgetPasswordPage.jsx
  src/pages/login/JoinPage.jsx
  src/pages/login/LoginPage.jsx
  src/store/Store.js
  src/store/action/CommonAction.js
  src/store/action/UserAction.js
  src/store/reducer/CommonReducer.js
  src/store/reducer/UserReducer.js
  src/store/type/CommonActionType.js
  src/store/type/UserActionType.js
Labels: 기능추가

#42 ✨ Feat/reels - 릴스 공유창, 더보기창, 좋아요 클릭 기능 구현
  package-lock.json
  public/assets/reels/bookmark_btn.svg
  public/assets/reels/comment_btn.svg
  public/assets/reels/email.svg
  public/assets/reels/facebook.svg
  public/assets/reels/like_btn.svg
  public/assets/reels/like_btn2.svg
  public/assets/reels/liked_btn.svg
  public/assets/reels/link.svg
  public/assets/reels/menu_btn.svg
  public/assets/reels/messenger.svg
  public/assets/reels/reels_profile.png
  public/assets/reels/search.svg
  public/assets/reels/share.svg
  public/assets/reels/share_btn.svg
  public/assets/reels/song.png
  public/assets/reels/threads.svg
  public/assets/reels/whatsapp.svg
  public/assets/reels/x.svg
  src/pages/Reels.jsx
  src/pages/ReelsComment.jsx
  src/pages/ReelsMenu.jsx
  src/pages/ReelsShare.jsx
Labels: 기능추가

#47 🐛 [검색탭] 화면 줄일 시, UI 버그 해결
  src/components/searchTab/SearchTab.jsx
Labels: 기능추가

#45 ✨ Feat/login - 회원가입 페이지 / 비밀번호 찾기 페이지 구현
  src/assets/login/facebook.svg
  src/assets/login/lock.svg
  src/components/login/InputBox.jsx
  src/components/login/JoinForm.jsx
  src/components/login/LoginForm.jsx
  src/components/login/MoreBox.jsx
  src/components/login/SubmitButton.jsx
  src/components/login/validateFields.js
  src/pages/login/ForgetPasswordPage.jsx
  src/pages/login/JoinPage.jsx
  src/pages/login/LoginPage.jsx
  src/store/action/UserAction.js
  src/store/reducer/UserReducer.js
  src/store/type/UserActionType.js
Labels: 기능추가

#48 ✨ firebase연동 완료 (회원가입 / 로그인)
  src/api/firebase/FirebaseUtils.js
  src/components/login/JoinForm.jsx
  src/components/login/LoginForm.jsx
  src/config/config.js
  src/store/reducer/CommonReducer.js
Labels: 기능추가

#49 ✨ Feat/reels - 리덕스 적용 및 인스타 api 연결
  src/App.jsx
  src/api/instagramAPI.js
  src/config/config.js
  src/pages/Reels/AuthCallback.jsx
  src/pages/Reels/Reels.jsx
  src/pages/Reels/ReelsComment.jsx
  src/pages/Reels/ReelsMenu.jsx
  src/pages/Reels/ReelsShare.jsx
  src/store/Store.js
  src/store/action/ReelsAction.js
  src/store/reducer/ReelsReducer.js
  src/store/type/ReelsActionType.js
Labels: 기능추가

#53 🚑app.js에서 reels import 중복 삭제
  src/App.jsx
Labels: 버그

#54 🚑app.js에서 이전버전 커밋이 merge된 부분 수정
  src/App.jsx
Labels: 버그

#56 💄 Feat/reels - 릴스 메인 컴포넌트 api 적용
  public/assets/reels/profile.png
  src/api/instagramAPI.js
  src/config/config.js
  src/pages/Reels/Reels.jsx
  src/store/action/ReelsAction.js
  src/store/reducer/ReelsReducer.js
Labels: 기능추가
